[package]
name = "flyQ"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.97"

[dev-dependencies]
tempfile = "3"