//const DEFAULT_SEGMENT_BYTES:u64 = 100;

pub const DEFAULT_INDEX_INTERVAL: u32 = 100;
pub const DEFAULT_MAX_SEGMENT_BYTES: u64 = 1024;
pub const DEFAULT_AUTO_CREATE_TOPICS_ENABLE: bool = true;
pub const DEFAULT_PARTITION_CNT: u32 = 1;
